let express=require("express")
const { login, adduser } = require("../controlers/usercont")
let { addprod, getprods, getprodbyid, getprodbycat, searchprod, updateprodimg,upload, deleteprod,updateprod } = require("../controlers/prodcon")
let { addcart, getcartitems, inccartqty, deccartqty, deletecartitem } = require("../controlers/cartcon")
let rt=new express.Router()
rt.post("/login",login)
rt.post("/reg",adduser)
rt.post("/addprod",upload.single("img"),addprod)
rt.get("/getprods",getprods)
rt.get("/getprodbyid/:id",getprodbyid)
rt.get("/getprodbycat/:cat",getprodbycat)
rt.get("/searchprod/:title",searchprod)
rt.put("/updateprodimg",upload.single("img"),updateprodimg)
rt.put("/updateprod",updateprod)
rt.delete("/delprod/:id",deleteprod)
rt.post("/addcart",addcart)
rt.get("/getcartitems/:uid",getcartitems)
rt.get("/inccartqty/:cid",inccartqty)
rt.get("/deccartqty/:cid",deccartqty)
rt.delete("/deletecartitem/:cid",deletecartitem)
module.exports=rt